/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

import javafx.stage.Stage;

public class App {

    public static void main(String[] args) {

    }

    public void start(Stage stage){

    }
}
